# To run this spider and save scraped data to a csv file, type into terminal:
#    scrapy crawl rctspider --set FEED_URI=items.csv --set FEED_FORMAT=csv

from scrapy.spider import Spider
from rct.items import rctItem
from scrapy.selector import Selector
from scrapy.contrib.loader import ItemLoader


###
# Helper function that gets the xpath for the text associated with a named field label.
# For example, from:
# <div class="field-label">Was attrition correlated with treatment status?</div>
# <div class="field">No</div>
# with the argument "Was attrition correlated with treatmetn status?" we could extract "No"
###
def xpathForField(label):
    # in english, this says:
    # "search the document for a div that has a child div of class field-label and make sure its text says label
    # "give me back the other child (with class field) of that parent div and give me his text"
    return '//div[div[@class="field-label"]/text()="' + label + '"]/div[@class="field"]/text()'

def xpathForUrl(label):
    # Same as above, but instead of going for the text of the child, descend into the child and grab the url (i.e. "href") from his link (i.e. "a").
    return '//div[div[@class="field-label"]/text()="' + label + '"]/div[@class="field"]/a/@href'    

## can't use the above with 'abstract', 'citation', and 'url' for relevant papers because it catches the other relevant papers
def xpathForRelevantPapersField(label):
    return '//fieldset[legend/text()="Relevant Papers"]//div[div[@class="field-label"]/text()="' + label + '"]/div[@class="field"]/text()'

## ditto, but for urls
def xpathForRelevantPapersUrl(label):
    return '//fieldset[legend/text()="Relevant Papers"]//div[div[@class="field-label"]/text()="' + label + '"]/div[@class="field"]/a/@href'    


class rctSpider(Spider):
    name = 'rct'
    allowed_domains = ['socialscienceregistry.org']
    start_urls=[
"https://www.socialscienceregistry.org/trials/34",
"https://www.socialscienceregistry.org/trials/439",
"https://www.socialscienceregistry.org/trials/320",
"https://www.socialscienceregistry.org/trials/817",
"https://www.socialscienceregistry.org/trials/960",
"https://www.socialscienceregistry.org/trials/231",
"https://www.socialscienceregistry.org/trials/40",
"https://www.socialscienceregistry.org/trials/156",
"https://www.socialscienceregistry.org/trials/634",
"https://www.socialscienceregistry.org/trials/937",
"https://www.socialscienceregistry.org/trials/97",
"https://www.socialscienceregistry.org/trials/13",
"https://www.socialscienceregistry.org/trials/11",
"https://www.socialscienceregistry.org/trials/895",
"https://www.socialscienceregistry.org/trials/437",
"https://www.socialscienceregistry.org/trials/441",
"https://www.socialscienceregistry.org/trials/600",
"https://www.socialscienceregistry.org/trials/618",
"https://www.socialscienceregistry.org/trials/225",
"https://www.socialscienceregistry.org/trials/597",
"https://www.socialscienceregistry.org/trials/234",
"https://www.socialscienceregistry.org/trials/442",
"https://www.socialscienceregistry.org/trials/644",
"https://www.socialscienceregistry.org/trials/950",
"https://www.socialscienceregistry.org/trials/444",
"https://www.socialscienceregistry.org/trials/16",
"https://www.socialscienceregistry.org/trials/583",
"https://www.socialscienceregistry.org/trials/668",
"https://www.socialscienceregistry.org/trials/8",
"https://www.socialscienceregistry.org/trials/716",
"https://www.socialscienceregistry.org/trials/479",
"https://www.socialscienceregistry.org/trials/584",
"https://www.socialscienceregistry.org/trials/445",
"https://www.socialscienceregistry.org/trials/402",
"https://www.socialscienceregistry.org/trials/945",
"https://www.socialscienceregistry.org/trials/36",
"https://www.socialscienceregistry.org/trials/695",
"https://www.socialscienceregistry.org/trials/114",
"https://www.socialscienceregistry.org/trials/563",
"https://www.socialscienceregistry.org/trials/461",
"https://www.socialscienceregistry.org/trials/571",
"https://www.socialscienceregistry.org/trials/200",
"https://www.socialscienceregistry.org/trials/447",
"https://www.socialscienceregistry.org/trials/172",
"https://www.socialscienceregistry.org/trials/293",
"https://www.socialscienceregistry.org/trials/88",
"https://www.socialscienceregistry.org/trials/488",
"https://www.socialscienceregistry.org/trials/615",
"https://www.socialscienceregistry.org/trials/561",
"https://www.socialscienceregistry.org/trials/766",
"https://www.socialscienceregistry.org/trials/435",
"https://www.socialscienceregistry.org/trials/636",
"https://www.socialscienceregistry.org/trials/647",
"https://www.socialscienceregistry.org/trials/722",
"https://www.socialscienceregistry.org/trials/38",
"https://www.socialscienceregistry.org/trials/52",
"https://www.socialscienceregistry.org/trials/448",
"https://www.socialscienceregistry.org/trials/87",
"https://www.socialscienceregistry.org/trials/449",
"https://www.socialscienceregistry.org/trials/623",
"https://www.socialscienceregistry.org/trials/613",
"https://www.socialscienceregistry.org/trials/452",
"https://www.socialscienceregistry.org/trials/343",
"https://www.socialscienceregistry.org/trials/487",
"https://www.socialscienceregistry.org/trials/180",
"https://www.socialscienceregistry.org/trials/451",
"https://www.socialscienceregistry.org/trials/750",
"https://www.socialscienceregistry.org/trials/414",
"https://www.socialscienceregistry.org/trials/666",
"https://www.socialscienceregistry.org/trials/48",
"https://www.socialscienceregistry.org/trials/51",
"https://www.socialscienceregistry.org/trials/566",
"https://www.socialscienceregistry.org/trials/53",
"https://www.socialscienceregistry.org/trials/26",
"https://www.socialscienceregistry.org/trials/602",
"https://www.socialscienceregistry.org/trials/237",
"https://www.socialscienceregistry.org/trials/852",
"https://www.socialscienceregistry.org/trials/416",
"https://www.socialscienceregistry.org/trials/491",
"https://www.socialscienceregistry.org/trials/285",
"https://www.socialscienceregistry.org/trials/741",
"https://www.socialscienceregistry.org/trials/522",
"https://www.socialscienceregistry.org/trials/977",
"https://www.socialscienceregistry.org/trials/626",
"https://www.socialscienceregistry.org/trials/365",
"https://www.socialscienceregistry.org/trials/109",
"https://www.socialscienceregistry.org/trials/637",
"https://www.socialscienceregistry.org/trials/17",
"https://www.socialscienceregistry.org/trials/803",
"https://www.socialscienceregistry.org/trials/537",
"https://www.socialscienceregistry.org/trials/518",
"https://www.socialscienceregistry.org/trials/81",
"https://www.socialscienceregistry.org/trials/262",
"https://www.socialscienceregistry.org/trials/65",
"https://www.socialscienceregistry.org/trials/317",
"https://www.socialscienceregistry.org/trials/105",
"https://www.socialscienceregistry.org/trials/459",
"https://www.socialscienceregistry.org/trials/567",
"https://www.socialscienceregistry.org/trials/314",
"https://www.socialscienceregistry.org/trials/340",
"https://www.socialscienceregistry.org/trials/136",
"https://www.socialscienceregistry.org/trials/492",
"https://www.socialscienceregistry.org/trials/705",
"https://www.socialscienceregistry.org/trials/333",
"https://www.socialscienceregistry.org/trials/569",
"https://www.socialscienceregistry.org/trials/964",
"https://www.socialscienceregistry.org/trials/170",
"https://www.socialscienceregistry.org/trials/517",
"https://www.socialscienceregistry.org/trials/531",
"https://www.socialscienceregistry.org/trials/660",
"https://www.socialscienceregistry.org/trials/899",
"https://www.socialscienceregistry.org/trials/961",
"https://www.socialscienceregistry.org/trials/687",
"https://www.socialscienceregistry.org/trials/194",
"https://www.socialscienceregistry.org/trials/454",
"https://www.socialscienceregistry.org/trials/774",
"https://www.socialscienceregistry.org/trials/630",
"https://www.socialscienceregistry.org/trials/528",
"https://www.socialscienceregistry.org/trials/443",
"https://www.socialscienceregistry.org/trials/486",
"https://www.socialscienceregistry.org/trials/570",
"https://www.socialscienceregistry.org/trials/350",
"https://www.socialscienceregistry.org/trials/493",
"https://www.socialscienceregistry.org/trials/568",
"https://www.socialscienceregistry.org/trials/586",
"https://www.socialscienceregistry.org/trials/494",
"https://www.socialscienceregistry.org/trials/155",
"https://www.socialscienceregistry.org/trials/61",
"https://www.socialscienceregistry.org/trials/607",
"https://www.socialscienceregistry.org/trials/338",
"https://www.socialscienceregistry.org/trials/252",
"https://www.socialscienceregistry.org/trials/73",
"https://www.socialscienceregistry.org/trials/608",
"https://www.socialscienceregistry.org/trials/530",
"https://www.socialscienceregistry.org/trials/688",
"https://www.socialscienceregistry.org/trials/456",
"https://www.socialscienceregistry.org/trials/655",
"https://www.socialscienceregistry.org/trials/458",
"https://www.socialscienceregistry.org/trials/358",
"https://www.socialscienceregistry.org/trials/742",
"https://www.socialscienceregistry.org/trials/229",
"https://www.socialscienceregistry.org/trials/532",
"https://www.socialscienceregistry.org/trials/168",
"https://www.socialscienceregistry.org/trials/529",
"https://www.socialscienceregistry.org/trials/450",
"https://www.socialscienceregistry.org/trials/466",
"https://www.socialscienceregistry.org/trials/828",
"https://www.socialscienceregistry.org/trials/731",
"https://www.socialscienceregistry.org/trials/516",
"https://www.socialscienceregistry.org/trials/533",
"https://www.socialscienceregistry.org/trials/675",
"https://www.socialscienceregistry.org/trials/23",
"https://www.socialscienceregistry.org/trials/627",
"https://www.socialscienceregistry.org/trials/573",
"https://www.socialscienceregistry.org/trials/21",
"https://www.socialscienceregistry.org/trials/579",
"https://www.socialscienceregistry.org/trials/639",
"https://www.socialscienceregistry.org/trials/368",
"https://www.socialscienceregistry.org/trials/578",
"https://www.socialscienceregistry.org/trials/896",
"https://www.socialscienceregistry.org/trials/222",
"https://www.socialscienceregistry.org/trials/638",
"https://www.socialscienceregistry.org/trials/43",
"https://www.socialscienceregistry.org/trials/349",
"https://www.socialscienceregistry.org/trials/536",
"https://www.socialscienceregistry.org/trials/932",
"https://www.socialscienceregistry.org/trials/476",
"https://www.socialscienceregistry.org/trials/342",
"https://www.socialscienceregistry.org/trials/370",
"https://www.socialscienceregistry.org/trials/125",
"https://www.socialscienceregistry.org/trials/745",
"https://www.socialscienceregistry.org/trials/556",
"https://www.socialscienceregistry.org/trials/580",
"https://www.socialscienceregistry.org/trials/525",
"https://www.socialscienceregistry.org/trials/468",
"https://www.socialscienceregistry.org/trials/495",
"https://www.socialscienceregistry.org/trials/983",
"https://www.socialscienceregistry.org/trials/113",
"https://www.socialscienceregistry.org/trials/290",
"https://www.socialscienceregistry.org/trials/714",
"https://www.socialscienceregistry.org/trials/572",
"https://www.socialscienceregistry.org/trials/810",
"https://www.socialscienceregistry.org/trials/635",
"https://www.socialscienceregistry.org/trials/165",
"https://www.socialscienceregistry.org/trials/477",
"https://www.socialscienceregistry.org/trials/498",
"https://www.socialscienceregistry.org/trials/500",
"https://www.socialscienceregistry.org/trials/697",
"https://www.socialscienceregistry.org/trials/426",
"https://www.socialscienceregistry.org/trials/585",
"https://www.socialscienceregistry.org/trials/323",
"https://www.socialscienceregistry.org/trials/969",
"https://www.socialscienceregistry.org/trials/631",
"https://www.socialscienceregistry.org/trials/582",
"https://www.socialscienceregistry.org/trials/779",
"https://www.socialscienceregistry.org/trials/653",
"https://www.socialscienceregistry.org/trials/501",
"https://www.socialscienceregistry.org/trials/30",
"https://www.socialscienceregistry.org/trials/467",
"https://www.socialscienceregistry.org/trials/587",
"https://www.socialscienceregistry.org/trials/633",
"https://www.socialscienceregistry.org/trials/469",
"https://www.socialscienceregistry.org/trials/490",
"https://www.socialscienceregistry.org/trials/308",
"https://www.socialscienceregistry.org/trials/790",
"https://www.socialscienceregistry.org/trials/916",
"https://www.socialscienceregistry.org/trials/539",
"https://www.socialscienceregistry.org/trials/614",
"https://www.socialscienceregistry.org/trials/834",
"https://www.socialscienceregistry.org/trials/632",
"https://www.socialscienceregistry.org/trials/145",
"https://www.socialscienceregistry.org/trials/924",
"https://www.socialscienceregistry.org/trials/505",
"https://www.socialscienceregistry.org/trials/689",
"https://www.socialscienceregistry.org/trials/935",
"https://www.socialscienceregistry.org/trials/132",
"https://www.socialscienceregistry.org/trials/41",
"https://www.socialscienceregistry.org/trials/330",
"https://www.socialscienceregistry.org/trials/507",
"https://www.socialscienceregistry.org/trials/678",
"https://www.socialscienceregistry.org/trials/642",
"https://www.socialscienceregistry.org/trials/730",
"https://www.socialscienceregistry.org/trials/667",
"https://www.socialscienceregistry.org/trials/541",
"https://www.socialscienceregistry.org/trials/331",
"https://www.socialscienceregistry.org/trials/509",
"https://www.socialscienceregistry.org/trials/344",
"https://www.socialscienceregistry.org/trials/429",
"https://www.socialscienceregistry.org/trials/404",
"https://www.socialscienceregistry.org/trials/167",
"https://www.socialscienceregistry.org/trials/543",
"https://www.socialscienceregistry.org/trials/656",
"https://www.socialscienceregistry.org/trials/711",
"https://www.socialscienceregistry.org/trials/677",
"https://www.socialscienceregistry.org/trials/550",
"https://www.socialscienceregistry.org/trials/540",
"https://www.socialscienceregistry.org/trials/617",
"https://www.socialscienceregistry.org/trials/410",
"https://www.socialscienceregistry.org/trials/604",
"https://www.socialscienceregistry.org/trials/28",
"https://www.socialscienceregistry.org/trials/643",
"https://www.socialscienceregistry.org/trials/819",
"https://www.socialscienceregistry.org/trials/984",
"https://www.socialscienceregistry.org/trials/405",
"https://www.socialscienceregistry.org/trials/641",
"https://www.socialscienceregistry.org/trials/795",
"https://www.socialscienceregistry.org/trials/436",
"https://www.socialscienceregistry.org/trials/686",
"https://www.socialscienceregistry.org/trials/554",
"https://www.socialscienceregistry.org/trials/605",
"https://www.socialscienceregistry.org/trials/611",
"https://www.socialscienceregistry.org/trials/559",
"https://www.socialscienceregistry.org/trials/502",
"https://www.socialscienceregistry.org/trials/5",
"https://www.socialscienceregistry.org/trials/6",
"https://www.socialscienceregistry.org/trials/9",
"https://www.socialscienceregistry.org/trials/685",
"https://www.socialscienceregistry.org/trials/10",
"https://www.socialscienceregistry.org/trials/15",
"https://www.socialscienceregistry.org/trials/510",
"https://www.socialscienceregistry.org/trials/560",
"https://www.socialscienceregistry.org/trials/24",
"https://www.socialscienceregistry.org/trials/481",
"https://www.socialscienceregistry.org/trials/37",
"https://www.socialscienceregistry.org/trials/704",
"https://www.socialscienceregistry.org/trials/39",
"https://www.socialscienceregistry.org/trials/45",
"https://www.socialscienceregistry.org/trials/911",
"https://www.socialscienceregistry.org/trials/62",
"https://www.socialscienceregistry.org/trials/59",
"https://www.socialscienceregistry.org/trials/60",
"https://www.socialscienceregistry.org/trials/96",
"https://www.socialscienceregistry.org/trials/66",
"https://www.socialscienceregistry.org/trials/67",
"https://www.socialscienceregistry.org/trials/68",
"https://www.socialscienceregistry.org/trials/69",
"https://www.socialscienceregistry.org/trials/72",
"https://www.socialscienceregistry.org/trials/58",
"https://www.socialscienceregistry.org/trials/76",
"https://www.socialscienceregistry.org/trials/79",
"https://www.socialscienceregistry.org/trials/671",
"https://www.socialscienceregistry.org/trials/80",
"https://www.socialscienceregistry.org/trials/86",
"https://www.socialscienceregistry.org/trials/89",
"https://www.socialscienceregistry.org/trials/770",
"https://www.socialscienceregistry.org/trials/99",
"https://www.socialscienceregistry.org/trials/104",
"https://www.socialscienceregistry.org/trials/102",
"https://www.socialscienceregistry.org/trials/115",
"https://www.socialscienceregistry.org/trials/900",
"https://www.socialscienceregistry.org/trials/128",
"https://www.socialscienceregistry.org/trials/129",
"https://www.socialscienceregistry.org/trials/130",
"https://www.socialscienceregistry.org/trials/133",
"https://www.socialscienceregistry.org/trials/140",
"https://www.socialscienceregistry.org/trials/144",
"https://www.socialscienceregistry.org/trials/150",
"https://www.socialscienceregistry.org/trials/151",
"https://www.socialscienceregistry.org/trials/159",
"https://www.socialscienceregistry.org/trials/161",
"https://www.socialscienceregistry.org/trials/162",
"https://www.socialscienceregistry.org/trials/515",
"https://www.socialscienceregistry.org/trials/173",
"https://www.socialscienceregistry.org/trials/175",
"https://www.socialscienceregistry.org/trials/179",
"https://www.socialscienceregistry.org/trials/286",
"https://www.socialscienceregistry.org/trials/183",
"https://www.socialscienceregistry.org/trials/184",
"https://www.socialscienceregistry.org/trials/186",
"https://www.socialscienceregistry.org/trials/187",
"https://www.socialscienceregistry.org/trials/700",
"https://www.socialscienceregistry.org/trials/188",
"https://www.socialscienceregistry.org/trials/190",
"https://www.socialscienceregistry.org/trials/191",
"https://www.socialscienceregistry.org/trials/196",
"https://www.socialscienceregistry.org/trials/198",
"https://www.socialscienceregistry.org/trials/201",
"https://www.socialscienceregistry.org/trials/204",
"https://www.socialscienceregistry.org/trials/205",
"https://www.socialscienceregistry.org/trials/210",
"https://www.socialscienceregistry.org/trials/211",
"https://www.socialscienceregistry.org/trials/215",
"https://www.socialscienceregistry.org/trials/217",
"https://www.socialscienceregistry.org/trials/218",
"https://www.socialscienceregistry.org/trials/219",
"https://www.socialscienceregistry.org/trials/220",
"https://www.socialscienceregistry.org/trials/221",
"https://www.socialscienceregistry.org/trials/223",
"https://www.socialscienceregistry.org/trials/227",
"https://www.socialscienceregistry.org/trials/662",
"https://www.socialscienceregistry.org/trials/230",
"https://www.socialscienceregistry.org/trials/594",
"https://www.socialscienceregistry.org/trials/241",
"https://www.socialscienceregistry.org/trials/250",
"https://www.socialscienceregistry.org/trials/251",
"https://www.socialscienceregistry.org/trials/253",
"https://www.socialscienceregistry.org/trials/268",
"https://www.socialscienceregistry.org/trials/277",
"https://www.socialscienceregistry.org/trials/278",
"https://www.socialscienceregistry.org/trials/280",
"https://www.socialscienceregistry.org/trials/282",
"https://www.socialscienceregistry.org/trials/284",
"https://www.socialscienceregistry.org/trials/287",
"https://www.socialscienceregistry.org/trials/297",
"https://www.socialscienceregistry.org/trials/301",
"https://www.socialscienceregistry.org/trials/329",
"https://www.socialscienceregistry.org/trials/303",
"https://www.socialscienceregistry.org/trials/304",
"https://www.socialscienceregistry.org/trials/305",
"https://www.socialscienceregistry.org/trials/313",
"https://www.socialscienceregistry.org/trials/318",
"https://www.socialscienceregistry.org/trials/319",
"https://www.socialscienceregistry.org/trials/332",
"https://www.socialscienceregistry.org/trials/334",
"https://www.socialscienceregistry.org/trials/336",
"https://www.socialscienceregistry.org/trials/337",
"https://www.socialscienceregistry.org/trials/379",
"https://www.socialscienceregistry.org/trials/621",
"https://www.socialscienceregistry.org/trials/346",
"https://www.socialscienceregistry.org/trials/352",
"https://www.socialscienceregistry.org/trials/353",
"https://www.socialscienceregistry.org/trials/354",
"https://www.socialscienceregistry.org/trials/355",
"https://www.socialscienceregistry.org/trials/362",
"https://www.socialscienceregistry.org/trials/367",
"https://www.socialscienceregistry.org/trials/371",
"https://www.socialscienceregistry.org/trials/381",
"https://www.socialscienceregistry.org/trials/386",
"https://www.socialscienceregistry.org/trials/388",
"https://www.socialscienceregistry.org/trials/676",
"https://www.socialscienceregistry.org/trials/401",
"https://www.socialscienceregistry.org/trials/403",
"https://www.socialscienceregistry.org/trials/408",
"https://www.socialscienceregistry.org/trials/411",
"https://www.socialscienceregistry.org/trials/415",
"https://www.socialscienceregistry.org/trials/417",
"https://www.socialscienceregistry.org/trials/419",
"https://www.socialscienceregistry.org/trials/421",
"https://www.socialscienceregistry.org/trials/728",
"https://www.socialscienceregistry.org/trials/422",
"https://www.socialscienceregistry.org/trials/424",
"https://www.socialscienceregistry.org/trials/428",
"https://www.socialscienceregistry.org/trials/430",
"https://www.socialscienceregistry.org/trials/680",
"https://www.socialscienceregistry.org/trials/768",
"https://www.socialscienceregistry.org/trials/985",
"https://www.socialscienceregistry.org/trials/762",
"https://www.socialscienceregistry.org/trials/640",
"https://www.socialscienceregistry.org/trials/669",
"https://www.socialscienceregistry.org/trials/674",
"https://www.socialscienceregistry.org/trials/749",
"https://www.socialscienceregistry.org/trials/682",
"https://www.socialscienceregistry.org/trials/683",
"https://www.socialscienceregistry.org/trials/815",
"https://www.socialscienceregistry.org/trials/659",
"https://www.socialscienceregistry.org/trials/725",
"https://www.socialscienceregistry.org/trials/692",
"https://www.socialscienceregistry.org/trials/650",
"https://www.socialscienceregistry.org/trials/918",
"https://www.socialscienceregistry.org/trials/719",
"https://www.socialscienceregistry.org/trials/729",
"https://www.socialscienceregistry.org/trials/684",
"https://www.socialscienceregistry.org/trials/809",
"https://www.socialscienceregistry.org/trials/169",
"https://www.socialscienceregistry.org/trials/727",
"https://www.socialscienceregistry.org/trials/721",
"https://www.socialscienceregistry.org/trials/788",
"https://www.socialscienceregistry.org/trials/792",
"https://www.socialscienceregistry.org/trials/511",
"https://www.socialscienceregistry.org/trials/521",
"https://www.socialscienceregistry.org/trials/767",
"https://www.socialscienceregistry.org/trials/738",
"https://www.socialscienceregistry.org/trials/751",
"https://www.socialscienceregistry.org/trials/732",
"https://www.socialscienceregistry.org/trials/713",
"https://www.socialscienceregistry.org/trials/737",
"https://www.socialscienceregistry.org/trials/247",
"https://www.socialscienceregistry.org/trials/756",
"https://www.socialscienceregistry.org/trials/558",
"https://www.socialscienceregistry.org/trials/934",
"https://www.socialscienceregistry.org/trials/941",
"https://www.socialscienceregistry.org/trials/740",
"https://www.socialscienceregistry.org/trials/929",
"https://www.socialscienceregistry.org/trials/949",
"https://www.socialscienceregistry.org/trials/78",
"https://www.socialscienceregistry.org/trials/391",
"https://www.socialscienceregistry.org/trials/598",
"https://www.socialscienceregistry.org/trials/754",
"https://www.socialscienceregistry.org/trials/842",
"https://www.socialscienceregistry.org/trials/777",
"https://www.socialscienceregistry.org/trials/622",
"https://www.socialscienceregistry.org/trials/975",
"https://www.socialscienceregistry.org/trials/853",
"https://www.socialscienceregistry.org/trials/739",
"https://www.socialscienceregistry.org/trials/946",
"https://www.socialscienceregistry.org/trials/289",
"https://www.socialscienceregistry.org/trials/27",
"https://www.socialscienceregistry.org/trials/382",
"https://www.socialscienceregistry.org/trials/46",
"https://www.socialscienceregistry.org/trials/808",
"https://www.socialscienceregistry.org/trials/769",
"https://www.socialscienceregistry.org/trials/805",
"https://www.socialscienceregistry.org/trials/826",
"https://www.socialscienceregistry.org/trials/773",
"https://www.socialscienceregistry.org/trials/782",
"https://www.socialscienceregistry.org/trials/291",
"https://www.socialscienceregistry.org/trials/784",
"https://www.socialscienceregistry.org/trials/793",
"https://www.socialscienceregistry.org/trials/902",
"https://www.socialscienceregistry.org/trials/813",
"https://www.socialscienceregistry.org/trials/610",
"https://www.socialscienceregistry.org/trials/785",
"https://www.socialscienceregistry.org/trials/791",
"https://www.socialscienceregistry.org/trials/927",
"https://www.socialscienceregistry.org/trials/471",
"https://www.socialscienceregistry.org/trials/818",
"https://www.socialscienceregistry.org/trials/786",
"https://www.socialscienceregistry.org/trials/796",
"https://www.socialscienceregistry.org/trials/799",
"https://www.socialscienceregistry.org/trials/829",
"https://www.socialscienceregistry.org/trials/897",
"https://www.socialscienceregistry.org/trials/981",
"https://www.socialscienceregistry.org/trials/830",
"https://www.socialscienceregistry.org/trials/816",
"https://www.socialscienceregistry.org/trials/827",
"https://www.socialscienceregistry.org/trials/679",
"https://www.socialscienceregistry.org/trials/780",
"https://www.socialscienceregistry.org/trials/843",
"https://www.socialscienceregistry.org/trials/49",
"https://www.socialscienceregistry.org/trials/850",
"https://www.socialscienceregistry.org/trials/967",
"https://www.socialscienceregistry.org/trials/889",
"https://www.socialscienceregistry.org/trials/898",
"https://www.socialscienceregistry.org/trials/958",
"https://www.socialscienceregistry.org/trials/887",
"https://www.socialscienceregistry.org/trials/844",
"https://www.socialscienceregistry.org/trials/82",
"https://www.socialscienceregistry.org/trials/821",
"https://www.socialscienceregistry.org/trials/906",
"https://www.socialscienceregistry.org/trials/804",
"https://www.socialscienceregistry.org/trials/781",
"https://www.socialscienceregistry.org/trials/485",
"https://www.socialscienceregistry.org/trials/736",
"https://www.socialscienceregistry.org/trials/620",
"https://www.socialscienceregistry.org/trials/893",
"https://www.socialscienceregistry.org/trials/894",
"https://www.socialscienceregistry.org/trials/845",
"https://www.socialscienceregistry.org/trials/103",
"https://www.socialscienceregistry.org/trials/846",
"https://www.socialscienceregistry.org/trials/116",
"https://www.socialscienceregistry.org/trials/888",
"https://www.socialscienceregistry.org/trials/925",
"https://www.socialscienceregistry.org/trials/943",
"https://www.socialscienceregistry.org/trials/696",
"https://www.socialscienceregistry.org/trials/812",
"https://www.socialscienceregistry.org/trials/726",
"https://www.socialscienceregistry.org/trials/266",
"https://www.socialscienceregistry.org/trials/822",
"https://www.socialscienceregistry.org/trials/771",
"https://www.socialscienceregistry.org/trials/107",
"https://www.socialscienceregistry.org/trials/933",
"https://www.socialscienceregistry.org/trials/840",
"https://www.socialscienceregistry.org/trials/921",
"https://www.socialscienceregistry.org/trials/913",
"https://www.socialscienceregistry.org/trials/798",
"https://www.socialscienceregistry.org/trials/930",
"https://www.socialscienceregistry.org/trials/963",
"https://www.socialscienceregistry.org/trials/905",
"https://www.socialscienceregistry.org/trials/171",
"https://www.socialscienceregistry.org/trials/763",
"https://www.socialscienceregistry.org/trials/931",
"https://www.socialscienceregistry.org/trials/433",
"https://www.socialscienceregistry.org/trials/652",
"https://www.socialscienceregistry.org/trials/907",
"https://www.socialscienceregistry.org/trials/939",
"https://www.socialscienceregistry.org/trials/942",
"https://www.socialscienceregistry.org/trials/473",
"https://www.socialscienceregistry.org/trials/970",
"https://www.socialscienceregistry.org/trials/947",
"https://www.socialscienceregistry.org/trials/392",
"https://www.socialscienceregistry.org/trials/962",
"https://www.socialscienceregistry.org/trials/551",
"https://www.socialscienceregistry.org/trials/47",
"https://www.socialscienceregistry.org/trials/971",
"https://www.socialscienceregistry.org/trials/919",
"https://www.socialscienceregistry.org/trials/377",
"https://www.socialscienceregistry.org/trials/954",
"https://www.socialscienceregistry.org/trials/300",
"https://www.socialscienceregistry.org/trials/387",
"https://www.socialscienceregistry.org/trials/957",
"https://www.socialscienceregistry.org/trials/19",
"https://www.socialscienceregistry.org/trials/973"
    ]

    def parse(self, response):
    	sel = Selector(response)
    	l = ItemLoader(item=rctItem(), selector=sel)
        l.add_xpath('rct_id', xpathForField("RCT ID"))
        l.add_xpath('registration_date', xpathForField("Initial registration date"))
        l.add_xpath('interventions', xpathForField("Intervention(s)"))
        l.add_xpath('clustering', xpathForField("Was the treatment clustered?"))
        l.add_xpath('irb_name', xpathForField("IRB Name"))
        l.add_xpath('irb_date', xpathForField("IRB Approval Date"))
        l.add_xpath('irb_number', xpathForField("IRB Approval Number"))
        l.add_xpath('intervention_completion_date', xpathForField('Intervention Completion Date'))
        l.add_xpath('data_collection_complete', xpathForField('Data Collection Complete?'))
        l.add_xpath('final_ss_clusters', xpathForField('Final Sample Size: Number of Clusters (unit of randomization)'))
        l.add_xpath('attrition', xpathForField('Was attrition correlated with treatment status?'))
        l.add_xpath('final_ss_observations', xpathForField('Final Sample Size: Total number of observations'))
        l.add_xpath('final_ss_by_arms', xpathForField('Final Sample Size (or number of clusters) by treatment arms'))
        l.add_xpath('clustered_se', xpathForField('Do all standard errors account for clustering?'))
        l.add_xpath('public_data_url', xpathForUrl('Public Data Url'))
        l.add_xpath('program_files', xpathForField('Program Files?'))
        l.add_xpath('program_files_url', xpathForField('Program Files Url'))
        l.add_xpath('data_collection_completion_date', xpathForField('Data Collection Completion Date'))
        l.add_xpath('relevant_papers_abstract', xpathForRelevantPapersField('Abstract')) 
        l.add_xpath('relevant_papers_citation', xpathForRelevantPapersField('Citation'))
        l.add_xpath('relevant_papers_url', xpathForRelevantPapersUrl('Url'))
        l.add_xpath('public_data', xpathForField('Public Data?'))
    	yield l.load_item()
   